basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: alohahoy@gmail.com
    name: Aleksej Barysnikov
    url: https://aleksejbarysnikov.netlify.app/
  description: This is my Receptionist's and Doctor's API in Golang
  title: medPortal API
  version: "1.0"
paths: {}
swagger: "2.0"
